 engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 36
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  csslist:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.py"
  - "**.css"
  - "**.js"
exclude_paths:
  - "tests/*"
  - "docs/*"
