sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install: "pip install -r requirements/dev.txt"

before_script:
  # Install JS dependencies
  - npm install -g bower less
  - bower install

script: python manage.py test
